# ********RoostGPT********

# Test generated by RoostGPT for test metering-postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /v2.0/metering/metering-labels/{metering_label_id}_delete for http method type DELETE 
# RoostTestHash=b1a615d400
# 
# 

# ********RoostGPT********
Feature: Delete Metering Label API Tests
  This feature file tests the DELETE endpoint of the Metering Label API to verify its functionality.

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Delete a Metering Label Successfully
    Given path 'v2.0/metering/metering-labels/<metering_label_id>'
    And request {}
    When method DELETE
    Then status 204
    And match response == null
    And assert responseHeaders != null

    Examples:
      | read('v2.0_metering_metering-labels_metering_label_id_delete.csv') |
