# ********RoostGPT********

# Test generated by RoostGPT for test metering-postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /v2.0/metering/metering-labels/{metering_label_id}_get for http method type GET 
# RoostTestHash=a7069bdb0c
# 
# 

# ********RoostGPT********
Here is the corrected and audited Gherkin feature file based on the provided instructions:

```gherkin
Feature: Show Metering Label
  This feature tests the GET method for fetching information about a specific metering label.

  Background:
    """
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Accept: 'application/json' }
    """
    
  Scenario Outline: Get metering label by ID
    Given path 'v2.0/metering/metering-labels/' + <metering_label_id>
    When method GET
    Then status 200
    And match response.metering_label == """
        #object
    """
    And match response.metering_label.id == """
        #string
    """
    And match response.metering_label.tenant_id == """
          value expecting Reponse loop key compliance × success.
***

above debugpayload.reply_Response--