# ********RoostGPT********

# Test generated by RoostGPT for test metering-postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /v2.0/metering/metering-labels/{metering_label_id}_get for http method type GET 
# RoostTestHash=a7069bdb0c
# 
# 

# ********RoostGPT********
Feature: Tests for Get Metering Label API
    Description: This feature file contains scenarios to test the Get Metering Label API endpoint.

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase

  Scenario Outline: Test valid retrieval of metering label information
    Given path '/v2.0/metering/metering-labels/<metering_label_id>'
    When method GET
    Then status 200
    And match response == """#object"""
    And match response.metering_label == """#object"""
    And match response.metering_label.id == """#string"""
    And match response.metering_label.tenant_id == """#string"""
    And match response.metering_label.description == """#string"""
    And match response.metering_label.name == """#string"""

    Examples:
      | read('v2.0_metering_metering-labels_metering_label_id_get.csv') |

  Scenario: Test invalid metering label ID
    Given path '/v2.0/metering/metering-labels/nonexistent-id'
    When method GET
    Then status 404
    And match response == null

  Scenario: Test metering label endpoint without ID
    Given path '/v2.0/metering/metering-labels/'
    When method GET
    Then status 400
    And match response == """#object"""
