# ********RoostGPT********

# Test generated by RoostGPT for test metering-postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /v2.0/metering/metering-labels/{metering_label_id}_get for http method type GET 
# RoostTestHash=a7069bdb0c
# 
# 

# ********RoostGPT********
Feature: Test API for Show Metering Label

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Verify retrieval of metering label using valid id
    Given path 'v2.0', 'metering', 'metering-labels', '<metering_label_id>'
    When method GET
    Then status 200
    And match response.metering_label == '#object'
    And match response.metering_label.id == '#string'
    And match response.metering_label.tenant_id == '#string'
    And match response.metering_label.description == '#string'
    And match response.metering_label.name == '#string'

    Examples:
      | read('v2.0_metering_metering-labels_metering_label_id_get.csv') |
