# ********RoostGPT********

# Test generated by RoostGPT for test metering-postman using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /v2.0/metering/metering-labels/{metering_label_id}_delete for http method type DELETE 
# RoostTestHash=b1a615d400
# 
# 

# ********RoostGPT********
Feature: Delete Metering Label
  This feature tests the DELETE operation on the /v2.0/metering/metering-labels/{metering_label_id} endpoint

  Background:
    """
    {
      "urlBase": karate.properties['API_HOST'],
      "headers": {
        "Accept": "application/json",
        "Authorization": "{{$processEnvironment.AUTH_TOKEN}}"
      }
    }
    """

    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Accept: "application/json", Authorization: "#(processEnvironment.AUTH_TOKEN)" }

  Scenario: Delete a metering label by ID
    Given path 'v2.0/metering/metering-labels/{metering_label_id}'
    When method DELETE
    Then status 204
    And match response == null
